#
# This script reads the LOGLIK from each simulation (generated by the output analysis) and reports it

# Need to specify how many simulations were there (n_simul) 100 in the paper

import argparse
import os
import sys
import dill
import numpy as np
import time 
from utils import * 
from inference_functions import *
from functions import *
from numpyro.infer import Predictive
import pandas as pd
import pickle


## read output
data_model_names=['Hawkes/']
inference_model_names=['LGCP_Hawkes/']
i=0
j=0
data_folder='data_' + data_model_names[i]
print('\n Data simulated from ', data_model_names[i],'\n')

print('\n Data inferred from ', inference_model_names[j],'\n')

#model_names=['LGCP/','LGCP_Hawkes/','Hawkes/','Poisson/']
#model_names=['Hawkes']
Total_LOGLIK=[];Total_LOGLIKB=[];Total_std_LOGLIKB=[];Total_std_LOGLIK=[]
Total_LOGLIK_space=[];Total_LOGLIKB_space=[];Total_std_LOGLIKB_space=[];Total_std_LOGLIK_space=[]
Total_LOGLIKC_space=[];Total_std_LOGLIKC_space=[];
Total_LOGLIKD_space=[];Total_std_LOGLIKD_space=[];
TOTAL_combined_LOGLIKA=[]; TOTAL_combined_LOGLIKB=[]

n_simul=100
#for i,n in enumerate(model_names):
for n in np.arange(n_simul):
	model_folder='model_'+inference_model_names[j]
	filename='output/simulation_comparison/'+data_folder+model_folder
	LOGLIK = pd.read_pickle(filename+'LOGLIK_'+str(n)+'.pkl')
	#print('LOGLIK size', LOGLIK['loglik_10'].shape)
	#print(LOGLIK.keys)
	if n%10==0:
		print('mean loglik for simulation A', n, np.mean(LOGLIK['loglik_10']))
		print('mean loglik for simulation B', n, np.mean(LOGLIK['loglikB_10']))
		
	#print(LOGLIK.keys())
	Total_LOGLIK=np.concatenate((Total_LOGLIK, LOGLIK['loglik_10']))
	Total_std_LOGLIK=np.concatenate((Total_std_LOGLIK, LOGLIK['loglik_std_10']))

	Total_LOGLIKB=np.concatenate((Total_LOGLIKB, LOGLIK['loglikB_10']))
	Total_std_LOGLIKB=np.concatenate((Total_std_LOGLIKB, LOGLIK['loglikB_std_10']))

	#TOTAL_combined_LOGLIKA=np.concatenate((TOTAL_combined_LOGLIKA, LOGLIK['LOGLIKA_combined_10']))
	#TOTAL_combined_LOGLIKB=np.concatenate((TOTAL_combined_LOGLIKB, LOGLIK['LOGLIKB_combined_10']))



print('TOTAL LOGLIKS \n')
print('For inference model', model_folder, 'mean total_LOGLIK A time and space among all simulations is ',np.round(np.mean(Total_LOGLIK),3))
print('For inference model', model_folder, 'st dev total_LOGLIK A time and space among all simulations is ',np.round(np.std(Total_LOGLIK),3))

print('For inference model', model_folder, 'mean total_LOGLIK B time and space among all simulations is ',np.round(np.mean(Total_LOGLIKB),3))
print('For inference model', model_folder, 'st dev total_LOGLIK B time and space among all simulations is ',np.round(np.std(Total_LOGLIKB),3))

#print('For inference model', model_folder, 'LOGLIK is ',np.mean(LOGLIK['EA_mean_t_10']))
	#df3 = pd.read_pickle(filename+'LOGLIK')





